### PR TITLE
microRusEFI with SD card

### PR DESCRIPTION
**Pull request by JRDMcLAREN**
- added sdcard slot J14
- removed spi flash U11
- added 2 pads to power some kind of BT or WIFI module
- added voltage selector JP3 for BT module, bridged as 3V3 by default
- added protection diode D44 for VDD-to-JP3
- added pads for CANH and CANL
- replaced some components and pins, (C2, D41, D42, U7, C23,C24,C27,C29, FB1, J19)
- small (tiny) SMD0402 caps was replaced by CAP ARRAY (CN1, CN2, CN3, CN4)
- fix some vias
- changed GND PAD on J3 for RTC battery, oval type, for better soldering
- changed footprint Molex_48_MRE.kicad_mod, new used one is Molex_48_MRE_R055.kicad_mod
- added microSD_HC_Wurth_693072010801.kicad_mod to rusefi_lib directory

### CODE REVIEW

**Comment by rusefillc** [comment]
this is a great, it should go live one day

**Comment by rusefillc** [comment]
@JRDMcLAREN please elaborate on "replaced some components and pins, (C2, D41, D42, U7, C23,C24,C27,C29, FB1, J19)"

**Comment by JRDMcLAREN** [comment]
Changed their positions and orientation for more space for SD Card slot.

**Comment by rusefillc** [comment]
See https://github.com/rusefi/kicad-libraries/issues/25

**Comment by rusefillc** [comment]
Something seems wrong with standard library? Why this change in all files:

image

**Pull request closed without merging**
