### PR TITLE
Outputs througth tle

### PR DESCRIPTION
**Pull request by dron0gus**
Screenshot from 2020-04-12 19-04-17
Change list:
- U9, U10 (additional outputs) moved to top.
- U9, U10 are now driven from TLE8888 (also diagnostic is possible)
- IGN inputs of TLE8888 are now connected to MCU
- IGN outputs of TLE are now routed to connector (through 0R resistors) - can save some $ not populating U32, U33.
- Hall sensor is powered from protected 5V1, not internal 5V
- Hall sensor optional resistors are now on top
- DFB11 to AV9 connection removed.
- silk cleanup

TODO:
- ~~change U9, U10 from smart switch (VNLD5090) to some cheap mosfet~~

### CODE REVIEW

**Comment by mck1117** [comment]
Why switch from VNLD to cheap mosfet? The VNLDs are protected and have active clamping, which jellybean FETs do not.

**Comment by mck1117** [comment]
Do we want to connect TLE enable pins for IGN/INJ, with pulldowns?

**Comment by dron0gus** [comment]
> Why switch from VNLD to cheap mosfet? The VNLDs are protected and have active clamping, which jellybean FETs do not.
TLE can protect external MOSFET too. But do not have active clamping.
It was just a suggestion. As we do not use STATUS output, why we need smart switch :)

**Comment by dron0gus** [comment]
Pull request was updated:
    -USB can be powered from AV4
    -TLE8888 INJ_EN and IGN_EN routed to STM32 PD11 and PD10
    -TLE8888 RST and STM32 NRST connected through 0R jumper
    -Test point for TLE8888 OUT7
    -DRC and ERC fixes

**Comment by rusefi** [comment]
@dron0gus "TLE8888 INJ_EN and IGN_EN routed to STM32 PD11 and PD10" - what are the potential usages of this?

**Comment by dron0gus** [comment]
> @dron0gus "TLE8888 INJ_EN and IGN_EN routed to STM32 PD11 and PD10" - what are the potential usages of this?

Safety reasons. If STM32 is restarted dues to some reasons default levels on its gpio PD11 and PD10 and pull-downs will disable TLE8888 outputs. Previously these enable pins were fixed high.

**Comment by mck1117** [comment]
> 
> 
> > @dron0gus "TLE8888 INJ_EN and IGN_EN routed to STM32 PD11 and PD10" - what are the potential usages of this?
> 
> Safety reasons. If STM32 is restarted dues to some reasons default levels on its gpio PD11 and PD10 and pull-downs will disable TLE8888 outputs. Previously these enable pins were fixed high.

Yes, exactly the same reasoning for why we connected the DIS pin from the ETB driver.  It's great if we have a small number of pins we can set to disable everything when something goes wrong.

**Pull request merged**
