### PR TITLE
Re-worked layout, wider traces, segregated ground current, opened area

### PR DESCRIPTION
**Pull request by DonaldBecker**
This is a re-worked board layout, based on an unmodified v0.3 schematic.

The following are the major changes
Wider traces for paths carrying significant current, especially supplies (5V, 3.3V), injectors and LS1/LS2
Minimum 8.5 mils traces for other signals
Segregated ground plane to avoid return current flow under the analog inputs
Opened areas for additional features, especially additional outputs from the TLE8888
Only pull-down resistors and clamps to 5V on the bottom side of the board

The segregated ground plane would be more effective with a dedicated sensor ground pin, but that (like many other changes) would require a schematic modification.

### CODE REVIEW

**Comment by rusefi** [comment]
@jharvey would you be available to review suggested alternative PCB? I believe you can check out https://github.com/DonaldBecker/hw_microRusEfi

**Comment by mck1117** [comment]
There are semi-official sensor ground pins.  The two large ground pins are intended as power ground, and the two small pins are intended as sensor ground.

**Comment by mck1117** [comment]
A few notes from a first look:
1) plated thru holes above the flat parts of the case are probably not a great idea, since they may short to the case.  I'm talking specifically about OUT15/16/17/18 and PD0/PC12/PC11/PC10.
2) A few of the silkscreens near R117 overlap pins
3) R49/R36 silk is under the connector
4) Do we want exposed pads underneath the tc4427s? The tc4427 has no exposed pad on the bottom.
5) Fiducial to the northwest of the TLE8888 misaligned with its silkscreen
6) There are a few schematic mods we may want to make soon around the trigger inputs and power supply - let's discuss these on Slack
6b) Same deal with the programming header - we could save a bit of area if we go down to a 1.27mm header.

Also - holy crap, it's only two layers! That's awesome!

**Comment by mck1117** [comment]
7) There's a stray trace that goes across the middle of the board on the bottom layer

image

**Comment by DonaldBecker** [comment]
The 8 wide pins are on the opposite end of the board from the TLE8888.  The majority of the current flows through the low side drivers on the TLE8888, making its ground return the key path.  That current previously went directly through the analog section.  Now it's directed around the analog section, largely on the edges of the board, but still crosses through the input connector.

That "trace" going across the board isn't on a copper layer -- it's marking a case (?) feature.

I don't have a sample of the case.  I'm assuming that the circuit board is held slightly above the case, and plated-through holes won't short out.  (Although wires soldered into the holes may be at risk.)

My plan is to add more of those through holes.  Especially for IGN1-4 (and the 6 similar gate driver outputs) to see if the TC4427 chips could be eliminated.

I know that the standard TC4427 doesn't have a ground pad, but the vias were on the original board layout.  Perhaps for thermal reasons, although I don't expect that the chips will be stressed by the 2mA-4mA drive current for an ignitor or smart coil.

**Comment by rusefi** [comment]
I believe the vias were on the original board layout with other TC4427 package in mind, not the SOIC-8 version

**Comment by rusefi** [comment]
What is the next step for this PR?

Are we aware of anyone planning to fab and assemble this PCB?

**Pull request merged**
